on:
  push:
    branches:
    - master
    tags:
    - '**'

name: push image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.0
    - name: extract tag
      id: vars
      run: echo ::set-output name=alpine_version::$(grep '^FROM alpine' Dockerfile  | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - run: echo "Pushing version ${{ steps.vars.outputs.alpine_version }}"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.18
      with:
        registry: docker.pkg.github.com	
        name: "ironpeakservices/iron-alpine/iron-alpine:${{ steps.vars.outputs.alpine_version }}"
        login-server: docker.pkg.github.com
        username: hazcod
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        tag: ${{ steps.vars.outputs.alpine_version }}
